services:
  db:
    image: postgres:latest
    container_name: my_db_compose
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_DB=araya
      - POSTGRES_USER=araya
      - POSTGRES_PASSWORD=araya